import { Plus_Jakarta_Sans as Plus } from "next/font/google";
import Home from "../page";
const plus = Plus({ weight: ["300", "400", "500", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Marco Task Management",
  description: "Generated by Next.js",
};

export default function RootLayout({ children, params }) {
  let title = `${params?.boards.toUpperCase()}`;
  return (
    <>
      <head>
        <title>{title}</title>
      </head>
      <body className={plus.className}>
        <Home>{children}</Home>
      </body>
    </>
  );
}
