import { Plus_Jakarta_Sans as Plus } from "next/font/google";
import Home from "../page";
const plus = Plus({ weight: ["300", "400", "500", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Marco Task Management",
  description: "Generated by Next.js",
};

export default function BoardsLayout({ children, params }) {
  let title = `${params?.boards.toUpperCase()}`;
  return (
    <>
      {/* <head>
        <title>{title}</title>
      </head> */}

      <Home>
        {children}
      </Home>
    </>
  );
}
