import { Plus_Jakarta_Sans as Plus } from "next/font/google";
import Home from "../page";
import { getBoards, getListBoards } from "@/fetching";
import style from "./layout.module.scss";
import {
  Dashboard,
  MainContent,
  MainTopMenu,
  TopMenu,
  TopMenuMobile,
  BoardEmpty,
  BoardNoEmpty,
} from "@/components";
const plus = Plus({ weight: ["300", "400", "500", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Marco Task Management",
  description: "Generated by Next.js",
};

export default async function BoardsLayout({ children, params }) {
  let title = `${params?.boards.toUpperCase()}`;
  const data = await getBoards(params.boards);
  const list = await getListBoards();

  return (
    <>
      <MainTopMenu>
        <TopMenu boardActive={data?.msg ? null : title} />
        <TopMenuMobile boardActive={data?.msg ? null : title} />
      </MainTopMenu>

      <div className={style.main}>
        <Dashboard listBoards={list} />
        {children}
      </div>
    </>
  );
}
