
// import { TopMenu, Dashboard, BoardEmpty } from "@/components";
// import ThemeProvider from "@/context/theme-provider";
// import { getBoards } from "@/fetching";
// import { Plus_Jakarta_Sans as Plus } from "next/font/google";
// import { Toaster } from "sonner";
// import Home from '../page'
// const plus = Plus({ weight: ["300", "400", "500", "700"], subsets: ["latin"] });

// export const metadata = {
//   title: "Children",
//   description: "Generated by Next.js",
// };


// export default function RootLayout({ children }) {
//     return (
//       <html lang="es">
//         <body className={plus.className}>
//           {/* <Home> */}
//           {children}
//           {/* </Home> */}
//         </body>
//       </html>
//     );
//   }